#!/usr/bin/env bash

if [ "$DKROOT" == "" ]
then
	echo "DKROOT not set, exiting"
	exit 1
fi
# run ac_tableau_container via command line
cd $DKROOT/AnalyticContainer
pwd

# cleanup exsinng containers  docker rm $(docker ps -q -f status=exited)
echo 'cleanup existng containers .. ignore errors'
sudo docker rmi -f ac_tableau_container
sudo docker rmi -f data_ac_tableau
sudo docker rm -f ac_tableau_container
sudo docker rm -f data_ac_tableau
sudo docker rm $(docker ps -a | grep ac_tableau_container)
sudo docker rm $(docker ps -a | grep data_ac_tableau)

dos2unix $DKROOT/AnalyticContainer/TableauContainer/run-selenium.sh
#build
echo 'building ac_tableau_container'
sudo docker build -f $DKROOT/AnalyticContainer/TableauContainer/Dockerfile -t ac_tableau_container .
echo 'building data_ac_tableau'
sudo docker run -d -v $DKROOT/AnalyticContainer/TableauContainer/docker-share --name="data_ac_tableau" ac_tableau_container:latest
echo 'adding config.json to data_ac_tableau'
sudo docker cp $DKROOT/DKModules/tests/json/tableau-container/tableau-container-node/docker-share/config.json data_ac_tableau:$DKROOT/AnalyticContainer/TableauContainer/docker-share/config.json
sudo docker cp $DKROOT/DKModules/tests/json/tableau-container/tableau-container-node/docker-share/test-container-workbook.twb  data_ac_tableau:$DKROOT/AnalyticContainer/TableauContainer/docker-share/test-container-workbook.twb

#run
echo 'running ac_tableau_container'
sudo docker run -e CONTAINER_INPUT_CONFIG_FILE_PATH="$DKROOT/DKModules/tests/json/tableau-container/tableau-container-node/docker-share" -e CONTAINER_INPUT_CONFIG_FILE_NAME="config.json" -e CONTAINER_OUTPUT_PROGRESS_FILE="progress.json" -e CONTAINER_OUTPUT_LOG_FILE="ac_logger.log" -e INSIDE_CONTAINER_FILE_MOUNT="$DKROOT/AnalyticContainer/TableauContainer" -e INSIDE_CONTAINER_FILE_DIRECTORY="$DKROOT/AnalyticContainer/TableauContainer/docker-share" --volumes-from data_ac_tableau ac_tableau_container:latest

echo 'copying volume back .. not sure why this does not happen automatically'
sudo docker cp data_ac_tableau:$DKROOT/AnalyticContainer/TableauContainer/docker-share/progress.json $DKROOT/AnalyticContainer/TableauContainer/docker-share/progress.json
sudo docker cp data_ac_tableau:$DKROOT/AnalyticContainer/TableauContainer/docker-share/ac_logger.log $DKROOT/AnalyticContainer/TableauContainer/docker-share/ac_logger.log

echo 'completed run ac_tableau_container, viewing data in data_ac_tableau'
sudo ls -als `docker inspect --format='{{(index .Mounts 0).Source}}' data_ac_tableau`
sudo cat `docker inspect --format='{{(index .Mounts 0).Source}}' data_ac_tableau`/ac_logger.log
sudo cat `docker inspect --format='{{(index .Mounts 0).Source}}' data_ac_tableau`/progress.json

echo 'view file system data_ac_tableau'
ls -als $DKROOT/AnalyticContainer/TableauContainer/docker-share/

echo 'the two above should be the same'
